"""5xx Server Error HTTP status codes.

This module contains HTTP status code exceptions for server error responses
(500-511).
"""

from ._core import HTTPStatus


# 5xx Server Errors
class HTTP_500_INTERNAL_SERVER_ERROR(HTTPStatus):
    """500 Internal Server Error response status code.

    Indicates that the server encountered an unexpected condition that
    prevented it from fulfilling the request.
    """

    status_code = 500
    message = "Internal Server Error"
    description = (
        "The server encountered an unexpected condition that "
        "prevented fulfilling the request."
    )


class HTTP_501_NOT_IMPLEMENTED(HTTPStatus):
    """501 Not Implemented response status code.

    Indicates that the server does not support the functionality required to
    fulfill the request.
    """

    status_code = 501
    message = "Not Implemented"
    description = (
        "The server does not support the functionality required "
        "to fulfill the request."
    )


class HTTP_502_BAD_GATEWAY(HTTPStatus):
    """502 Bad Gateway response status code.

    Indicates that the server, while acting as a gateway or proxy, received an
    invalid response from an inbound server it accessed while attempting to
    fulfill the request.
    """

    status_code = 502
    message = "Bad Gateway"
    description = (
        "The server received an invalid response from the upstream server."
    )


class HTTP_503_SERVICE_UNAVAILABLE(HTTPStatus):
    """503 Service Unavailable response status code.

    Indicates that the server is currently unable to handle the request due to
    a temporary overload or scheduled maintenance.
    """

    status_code = 503
    message = "Service Unavailable"
    description = "The server is temporarily unable to handle the request."


class HTTP_504_GATEWAY_TIMEOUT(HTTPStatus):
    """504 Gateway Timeout response status code.

    Indicates that the server, while acting as a gateway or proxy, did not
    receive a timely response from an upstream server it needed to access in
    order to complete the request.
    """

    status_code = 504
    message = "Gateway Timeout"
    description = (
        "The gateway server did not receive a timely response "
        "from the upstream server."
    )


class HTTP_505_HTTP_VERSION_NOT_SUPPORTED(HTTPStatus):
    """505 HTTP Version Not Supported response status code.

    Indicates that the server does not support, or refuses to support, the
    major version of HTTP that was used in the request message.
    """

    status_code = 505
    message = "HTTP Version Not Supported"
    description = (
        "The server does not support the HTTP protocol version "
        "used in the request."
    )


class HTTP_506_VARIANT_ALSO_NEGOTIATES(HTTPStatus):
    """506 Variant Also Negotiates response status code.

    Indicates that the server has an internal configuration error: the chosen
    variant resource is configured to engage in transparent content
    negotiation itself.
    """

    status_code = 506
    message = "Variant Also Negotiates"
    description = "The server has a configuration error in content negotiation."


class HTTP_507_INSUFFICIENT_STORAGE(HTTPStatus):
    """507 Insufficient Storage response status code.

    Indicates that the server is unable to store the representation needed to
    complete the request.
    """

    status_code = 507
    message = "Insufficient Storage"
    description = (
        "The server is unable to store the representation needed "
        "to complete the request."
    )


class HTTP_508_LOOP_DETECTED(HTTPStatus):
    """508 Loop Detected response status code.

    Indicates that the server terminated an operation because it encountered
    an infinite loop while processing a request.
    """

    status_code = 508
    message = "Loop Detected"
    description = (
        "The server detected an infinite loop while processing the request."
    )


class HTTP_510_NOT_EXTENDED(HTTPStatus):
    """510 Not Extended response status code.

    Indicates that further extensions to the request are required for the
    server to fulfill it.
    """

    status_code = 510
    message = "Not Extended"
    description = (
        "Further extensions to the request are required for the "
        "server to fulfill it."
    )


class HTTP_511_NETWORK_AUTHENTICATION_REQUIRED(HTTPStatus):
    """511 Network Authentication Required response status code.

    Indicates that the client needs to authenticate to gain network access.
    This status code is not generated by origin servers but by intercepting
    proxies.
    """

    status_code = 511
    message = "Network Authentication Required"
    description = "The client needs to authenticate to gain network access."


__all__ = [
    "HTTP_500_INTERNAL_SERVER_ERROR",
    "HTTP_501_NOT_IMPLEMENTED",
    "HTTP_502_BAD_GATEWAY",
    "HTTP_503_SERVICE_UNAVAILABLE",
    "HTTP_504_GATEWAY_TIMEOUT",
    "HTTP_505_HTTP_VERSION_NOT_SUPPORTED",
    "HTTP_506_VARIANT_ALSO_NEGOTIATES",
    "HTTP_507_INSUFFICIENT_STORAGE",
    "HTTP_508_LOOP_DETECTED",
    "HTTP_510_NOT_EXTENDED",
    "HTTP_511_NETWORK_AUTHENTICATION_REQUIRED",
]
