name: Linting

on: [push, pull_request, workflow_dispatch]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        uses: astral-sh/ruff-action@v3
        with:
          args: check
      - name: Check Formatting
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check
